// <auto-generated />
using System;
using EFCoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230823010921_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreApi.Models.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adfc1ffb-0066-4bf6-9103-0249d289d065"),
                            Age = 25,
                            EmailAddress = "JhonDoe@gmail.com",
                            FirstName = "Jhon",
                            LastName = "doe"
                        },
                        new
                        {
                            Id = new Guid("2122f873-1851-4514-90db-52d7924185ce"),
                            Age = 30,
                            EmailAddress = "JacobHilderth@gmail.com",
                            FirstName = "Jacob",
                            LastName = "Hilderth"
                        },
                        new
                        {
                            Id = new Guid("721b216b-cef0-4c1e-8184-e7cfcccaec0c"),
                            Age = 30,
                            EmailAddress = "JacobHilderth@gmail.com",
                            FirstName = "Jacob",
                            LastName = "Hilderth"
                        },
                        new
                        {
                            Id = new Guid("dbb8fdbf-44d9-4c49-b600-99e5864bf1be"),
                            Age = 22,
                            EmailAddress = "AlexWilliam@gmail.com",
                            FirstName = "Alexandra",
                            LastName = "William"
                        },
                        new
                        {
                            Id = new Guid("d6c4b89b-1bb3-4791-acd2-64af319e9dc3"),
                            Age = 27,
                            EmailAddress = "JonitaPeter@gmail.com",
                            FirstName = "Jonita",
                            LastName = "Peter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
